// Pins the main-guard on scripts/validation/build-oci.mjs: importing the
// module (as the adversarial tar-extraction tests do, to exercise
// extractBuildContext) must be side-effect free — no docker build, no docker
// save, no evidence write. An import that executed the main body would
// regenerate docs/evidence/oci-digest-bundle-<sha>.json with a fresh
// startedAt (and possibly a working-tree build context), silently corrupting
// the digest-bound evidence chain and breaking test hermeticity.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile, readdir, stat } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "../..");

function sha256Hex(contents: string): string {
  return createHash("sha256").update(contents).digest("hex");
}

test("importing build-oci.mjs runs no build and writes no evidence", async () => {
  const evidenceDir = resolve(root, "docs/evidence");
  const bundles = (await readdir(evidenceDir)).filter((name) => name.startsWith("oci-digest-bundle-")).sort();
  const latest = bundles[bundles.length - 1];
  assert.ok(latest, "a digest bundle must exist before this test runs (generated by `pnpm oci:build`)");
  const bundlePath = resolve(evidenceDir, latest);
  const beforeHash = sha256Hex(await readFile(bundlePath, "utf8"));
  const beforeMtime = (await stat(bundlePath)).mtimeMs;

  const mod = await import("../../scripts/validation/build-oci.mjs");

  assert.equal(typeof mod.extractBuildContext, "function", "extractBuildContext must remain exported for the tar-extraction tests");
  const afterHash = sha256Hex(await readFile(bundlePath, "utf8"));
  const afterMtime = (await stat(bundlePath)).mtimeMs;
  assert.equal(afterHash, beforeHash, "importing build-oci.mjs must not regenerate the digest bundle");
  assert.equal(afterMtime, beforeMtime, "importing build-oci.mjs must not touch the digest bundle");
});
