// Cross-checks the OCI digest bundle and the reproducible build path: the
// Dockerfile must pin both stages by digest, and the latest committed bundle
// (when present) must record the real image hash and passing assertions.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "../..");

test("containers/Dockerfile pins both base stages by digest", async () => {
  const dockerfile = await readFile(resolve(root, "containers/Dockerfile"), "utf8");
  const pinned = dockerfile.match(/FROM node:22\.23\.2-bookworm-slim@sha256:[0-9a-f]{64} AS (?:dependencies|runtime)/g) ?? [];
  assert.equal(pinned.length, 2, "both stages must pin node:22.23.2-bookworm-slim by digest");
});

test("containers/Dockerfile installs production dependencies only in the runtime stage", async () => {
  const dockerfile = await readFile(resolve(root, "containers/Dockerfile"), "utf8");
  assert.match(dockerfile, /pnpm install --prod --frozen-lockfile/, "the runtime stage must install production dependencies only");
  assert.ok(!dockerfile.includes("COPY --from=build /workspace/node_modules"), "the runtime stage must not copy the dev-toolchain node_modules from the build stage");
});

test("build-oci.mjs and the digest bundle generator are the only OCI entry points", async () => {
  const scripts = await readdir(resolve(root, "scripts/validation"));
  assert.ok(scripts.includes("build-oci.mjs"));
  assert.ok(scripts.includes("oci-subject-manifest.mjs"));
});

test("the latest committed digest bundle records real hashes and passing assertions", async (t) => {
  const bundles = (await readdir(resolve(root, "docs/evidence"))).filter((name) => name.startsWith("oci-digest-bundle-"));
  if (bundles.length === 0) {
    t.skip("no digest bundle committed yet; generated by `pnpm oci:build`");
    return;
  }
  const latest = [...bundles].sort().pop();
  assert.ok(latest, "a bundle file must be selected");
  const bundle = JSON.parse(await readFile(resolve(root, "docs/evidence", latest), "utf8"));
  assert.equal(bundle.recordKind, "oci-digest-bundle");
  assert.match(bundle.subject.identifiers.digest, /^sha256:[0-9a-f]{64}$/);
  assert.equal(typeof bundle.image.artifactTar.sha256, "string");
  assert.equal(bundle.image.artifactTar.sha256.length, 64);
  assert.ok(bundle.assertions.nonRootUser && bundle.assertions.noSecretEnv && bundle.assertions.exposes8080 && bundle.assertions.linuxImage);
  const dockerfileHash = createHash("sha256").update(await readFile(resolve(root, "containers/Dockerfile"), "utf8")).digest("hex");
  assert.equal(bundle.sourceHashes.dockerfile, dockerfileHash, "bundle dockerfile hash matches the committed file");
});

test("the committed PG-03 gate manifest binds the real policy and validator hashes", async (t) => {
  let manifest;
  try {
    manifest = JSON.parse(await readFile(resolve(root, "docs/evidence/oci-subject-local.json"), "utf8"));
  } catch {
    t.skip("PG-03 manifest not committed yet; generated by `pnpm oci:build`");
    return;
  }
  assert.equal(manifest.gateId, "PG-03");
  // The gate lifts exactly when an authorized container live run exists whose
  // subject digest equals the bundle's image ID; otherwise it stays blocked.
  const evidenceDir = resolve(root, "docs/evidence");
  // Mirror the manifest's lift logic exactly: only a ci-build bundle plus a
  // matching authorized container run lifts the gate; a local authorized run
  // never does.
  const bundleFiles = (await readdir(evidenceDir)).filter((name) => name.startsWith("oci-digest-bundle-") && name.endsWith(".json"));
  const ciBundles = [];
  for (const name of bundleFiles) {
    const candidate = JSON.parse(await readFile(resolve(evidenceDir, name), "utf8"));
    if (candidate.recordKind === "oci-digest-bundle" && candidate.subject?.environment === "ci-build"
      && candidate.assertions?.nonRootUser && candidate.assertions?.noSecretEnv && candidate.assertions?.exposes8080 && candidate.assertions?.linuxImage) {
      ciBundles.push(candidate);
    }
  }
  const newestCi = ciBundles.sort((left, right) => (left.buildMetadata?.startedAt ?? "").localeCompare(right.buildMetadata?.startedAt ?? "")).at(-1);
  const verifiedDigest = newestCi?.image?.imageId;
  let exactRun;
  if (verifiedDigest) {
    const containerLive = (await readdir(evidenceDir)).filter((name) => name.startsWith("container-live-lane-") && name.endsWith(".json")).sort();
    for (const name of containerLive) {
      const record = JSON.parse(await readFile(resolve(evidenceDir, name), "utf8"));
      if (record.mode === "authorized-run" && record.subject?.identifiers?.digest === verifiedDigest && record.summary?.failed === 0) {
        exactRun = record;
        break;
      }
    }
  }
  const expectedGateResult = exactRun ? "pass" : "blocked";
  assert.equal(manifest.gateResult, expectedGateResult, `PG-03 must be ${expectedGateResult} — the exact-subject container live run is ${exactRun ? "retained" : "absent"}`);
  const policySha = createHash("sha256").update(await readFile(resolve(root, "deploy/poc-policy.yaml"), "utf8")).digest("hex");
  assert.equal(manifest.policy.policySha256, policySha);
  const validatorSha = createHash("sha256").update(await readFile(resolve(root, "scripts/validation/validate-evidence-bundle.mjs"), "utf8")).digest("hex");
  assert.equal(manifest.policy.validatorSha256, validatorSha);
  assert.equal(manifest.policy.evaluationMode, "semantic-validator");
});

test("evidence records reference a real code-under-test commit", async (t) => {
  const records = (await readdir(resolve(root, "docs/evidence"))).filter((name) => /-(?:local|lane|subject)/.test(name) && name.endsWith(".json"));
  if (records.length === 0) {
    t.skip("no evidence records committed yet");
    return;
  }
  for (const name of records.slice(0, 5)) {
    const record = JSON.parse(await readFile(resolve(root, "docs/evidence", name), "utf8"));
    const recorded = record.subject?.identifiers?.commit;
    if (typeof recorded === "string" && /^[0-9a-f]{12,}$/.test(recorded)) {
      const exists = execFileSync("git", ["rev-parse", "--verify", "--quiet", `${recorded}^{commit}`], { cwd: root, encoding: "utf8" }).trim();
      assert.ok(exists.length > 0, `${name} records commit ${recorded} which must exist in git history`);
    }
  }
});
